apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: server-container
          image: meetdev.azurecr.io/devconnect-backend:1c1d8d5
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: server-cm
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: CLOUDINARY_API_SECRET
            - name: DEVCONNECT_TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: DEVCONNECT_TOKEN_KEY
            - name: EMAIL_PASS_KEY
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: EMAIL_PASS_KEY
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: DB_URL
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server-app
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-cm
data:
  PORT: "4000"
  DEVCONNECT_EMAIL: "meetoz309@gmail.com"
