apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: server-servicemonitor
  namespace: monitoring
  labels:
   release: kube-prometheus-stack
spec:
  endpoints:
    - interval: 15s
      port: http
      scrapeTimeout: 10s
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: server
